### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cyouh95** [mel-g/TeaCozy#5]
(Exceeds Expectations)

Nice job with this project! It looks like you have a good understanding of how HTML and CSS work together for display of content. You were able to recreate all the main components of this webpage so well done! Great job with the use of classes and IDs for styling your elements as well as for creating hyperlinks! And keep up the good work on the formatting and commenting of your code.

As a further challenge, try creating your own page from scratch without the use of any specs or template. You definitely already have a good sense of how to organize and structure your code - this will be great practice for continuing to build your skills! Happy coding!

**Comment by mel-g** [comment]
Thanks for the feedback! I'll give the challenge a go 😀 .
